version: "3"

services:
  postgres:
    image: postgres:14
    expose:
      - ${PG_EXPOSE_PORT}
    ports:
      - ${PG_EXPOSE_PORT}:${PG_RUN_PORT}
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    command: -p ${PG_RUN_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: ${PG_RUN_PORT}
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=app
      - --batch-size=20
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 15s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: ${PG_RUN_PORT}
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000
