name: Deploy with Acala RPC (staging)

on:
  workflow_dispatch:
    inputs:
      subqlAccessToken:
        description: 'Subquery access token https://doc.subquery.network/publish/ipfs/#prepare-your-subql-access-token'
        required: true
        type: string

jobs:
  publish:
    name: IPFS publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Generate schema type
        run: pnpm codegen

      - name: Publish to IPFS
        run: pnpm build && pnpm ipfs:publish -f acala-staging.yaml
        env:
          SUBQL_ACCESS_TOKEN: ${{ github.event.inputs.subqlAccessToken }}